export enum ErrorCode {
  // Common
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // User
  USER_NOT_FOUND = 'USER_NOT_FOUND',

  // Project
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',

  // Sketch
  SKETCH_NOT_FOUND = 'SKETCH_NOT_FOUND',
  SKETCH_REQUIRED = 'SKETCH_REQUIRED',

  // Moodboard
  MOODBOARD_NOT_FOUND = 'MOODBOARD_NOT_FOUND',
  MOODBOARD_REQUIRED = 'MOODBOARD_REQUIRED',

  // Prompt
  PROMPT_NOT_FOUND = 'PROMPT_NOT_FOUND',

  // Rendering
  RENDERING_NOT_FOUND = 'RENDERING_NOT_FOUND',
  RENDERING_DUPLICATE = 'RENDERING_DUPLICATE',

  // Gemini / External API
  GEMINI_API_FAILED = 'GEMINI_API_FAILED',
  GEMINI_NO_IMAGE = 'GEMINI_NO_IMAGE',
  GEMINI_AUTH_ERROR = 'GEMINI_AUTH_ERROR',
  GEMINI_RATE_LIMITED = 'GEMINI_RATE_LIMITED',
  GEMINI_QUEUE_FULL = 'GEMINI_QUEUE_FULL',

  // File
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FILE_SAVE_FAILED = 'FILE_SAVE_FAILED',
}
